README.md, lib/fastly/service.rb
This addresses #50 through improved documentation.
We didn't have this documented at all, so customers would not be aware of the possible performance impact.  We also add pointers to the Fastly API documentation for further reading.
=> Improve examples of purging

lib/fastly/client.rb
This adds one line so that Net::HTTP is not always started with the `use_ssl: true`.
Since https://github.com/fastly/fastly-ruby/commit/350c3d1ae74b25011aa2998bc140b49d34ef0da4 we've _always_ passed `use_ssl: true` to Net::HTTP in our client init. I ran into a slightly annoying issue while doing some testing where Net::HTTP throws SSL errors if you  provide a HTTP base_uri instead of HTTPS.
=> Detect if client base_uri is HTTPS

lib/fastly.rb
[This endpoint][1] is returning a 404 for me regardless of whether I'm authenticated or not.
[1]: https://api.fastly.com/commands
=> Remove `Fastly.commands`

lib/fastly/client.rb
NameError: uninitialized constant Fastly::Client::OpenSSL
from /Users/thomas/.chefdk/gem/ruby/2.1.0/gems/fastly-1.2.2/lib/fastly/client.rb:21:in `initialize'
from /Users/thomas/.chefdk/gem/ruby/2.1.0/gems/fastly-1.2.2/lib/fastly/fetcher.rb:19:in `new'
from /Users/thomas/.chefdk/gem/ruby/2.1.0/gems/fastly-1.2.2/lib/fastly/fetcher.rb:19:in `client'
from /Users/thomas/.chefdk/gem/ruby/2.1.0/gems/fastly-1.2.2/lib/fastly.rb:48:in `initialize'
from (irb):3:in `new'
from (irb):3
from /opt/chefdk/embedded/bin/irb:11:in `<main>'
=> require 'openssl'

lib/fastly/backend.rb, lib/fastly/healthcheck.rb, lib/fastly/s3_logging.rb, lib/fastly/syslog.rb
Hello,
I'm not sure if there's a styleguide or anything so let me know if I should switch things around. Also, `shield` isn't in the API docs but I successfully set it via the API (though I had pulled out the internal values e.g. `amsterdam-nl` for AMS).
backend, healthcheck, s3 and syslog were missing fields that were
settable in the API.
=> Update gem with missing fields

lib/fastly/s3_logging.rb, lib/fastly/syslog.rb
Hi again,
Here are some more fields. In this case domain and redundancy don't show up in the API docs but they do in the UI. Unfortunately, our config is set to an empty string so that's the extent of testing I've done with these.
Thanks!
=> Added missing fields to S3Logging and syslog

lib/fastly/belongs_to_service_and_version.rb
Hello,
I'm not sure if there's a styleguide or something so do let me know if I should change things around.
The API allows names with spaces but GETs and PUTs use the name
unescaped in the URL and the client cannot reference/search for these
resources correctly. The client now escapes the name when it is a
component in the URL, but not when used in request data.
=> URL escape names when used in URLs

README.md, lib/fastly.rb, lib/fastly/client.rb, lib/fastly/service.rb, test/api_key_test.rb
Allows users to do "soft" purging.
Also switches to 'new' method of purging using PURGE verb.
=> Soft purge

lib/fastly/client.rb
Provides a named user agent in `headers`
=> Add a user agent key/value pair to client headers

lib/fastly.rb, lib/fastly/dictionary.rb, lib/fastly/version.rb
https://docs.fastly.com/guides/edge-dictionaries/about-edge-dictionaries
I've added an optional `pluralize` method which can be used to specify the correct way to create the plural form for listing a resource.
This first implementation of Edge Dictionaries is deliberately basic while I'm getting to grips with this codebase. I'll probably be adding some more after this.
Happy to add some tests for this code but I don't really know where to start.
=> Add Edge Dictionaries

lib/fastly/version.rb
Even if VCL was not correct `validate` was always returning true.
This fix will return entire hash with `status` and `msg`.
Before:
```
irb(main):001:0> require 'fastly'
irb(main):002:0> fastly  = Fastly.new({:api_key => 'XYZ'})
irb(main):003:0> service = fastly.get_service('ABC')
irb(main):004:0> service.version.validate
=> true
```
After this fix:
```
irb(main):001:0> require 'fastly'
irb(main):002:0> fastly  = Fastly.new({:api_key => 'XYZ'})
irb(main):003:0> service = fastly.get_service('ABC')
irb(main):004:0> service.version.validate
=> {"status"=>"ok"}
```
or:
```
irb(main):001:0> require 'fastly'
irb(main):002:0> fastly  = Fastly.new({:api_key => 'XYZ'})
irb(main):003:0> service = fastly.get_service('ABC')
irb(main):004:0> service.version.validate
=> {"msg"=>"No VCL named 'test.vcl' …
```
=> Validate was always returning true

lib/fastly/version.rb
Adding back `:locked` to `version.rb`, since the logic in `locked?` was failing without it. Tested on my machine in Ruby 2.2.3p173. 
More context in issue #47
=> Reintroduced :locked so the version.locked? check works

lib/fastly.rb, test/fastly/client_test.rb
Per our earlier discussion with Thom and Josh Lane, the absence of 'user' as an option should raise an error.
=> Raised ArgumentError if api_key or user/pass are not passed in. 

lib/fastly/client.rb, lib/fastly/dictionary.rb, test/fastly/dictionary_test.rb
Returns a specific `Fastly::DictionaryItem`
=> add Fastly::Dictionary#item

lib/fastly/client.rb
the purge function doesn't seem to work when purging https url's, this patch fixes that problem in a backward compatible way
=> add https support to purge function

lib/fastly.rb, lib/fastly/acl.rb, lib/fastly/acl_entry.rb, test/fastly/acl_entry_test.rb, test/fastly/acl_test.rb
ACL and ACLEntry API support
- `singularize` class method
- tests for ACL and managing entries from the ACL instances
- tests for ACL entries (fully instantiated)
- linted the new files
@schisamo @lanej
=> Add ACL and ACL Entry Support

gemfiles/ruby_1.9.gemfile
This fixes a dependency problem with ruby versions older than 2.0. See https://travis-ci.org/fastly/fastly-ruby/builds/176106718
=> use public_suffix version 1.4.6 for ruby 1.9

README.md, lib/fastly/client.rb, lib/fastly/gem_version.rb
This feature allows verbose HTTP debug logs to be printed to a specified output.
=> Support for HTTP debug logs

lib/fastly/s3_logging.rb, lib/fastly/syslog.rb
This will enable specifying a `message_type` of `blank` which is needed for JSON formatted log lines.
Signed-off-by: Seth Chisamore <schisamo@chef.io>
/cc @thommahoney @lanej @rhass @wrightp
=> Add `message_type` support to logging resources

lib/fastly.rb, lib/fastly/papertrail_logging.rb
Add support for streaming logs to Papertrail, based on the S3Logging class.
Based on the [docs](https://docs.fastly.com/api/logging#logging_papertrail), the Papertrail-specific params are:
```
address	string	An hostname or IPv4 address.
name	string	The name of the papertrail rule.
port	integer	The port number.
```
Not clear in the docs, but required in practice: 
```
hostname	string
```
I basically copy-pasted the S3Logging class, updated the attributes, and copied the `*_s3_logging` methods in fastly.rb. There don't seem to be any specific tests around `S3Logging` so I didn't make any for `PapertrailLogging` either.
=> Support Papertrail logging endpoints

lib/fastly/syslog.rb, test/fastly/syslog_test.rb
The "response_conditions" attribute on syslog should be "response_condition"
according to the API documentation at https://docs.fastly.com/api/logging#logging_syslog.
=> Fix syslog response_condition attribute

lib/fastly.rb, test/stats_test.rb
Adds a :by_month option to usage() for querying the Fastly Stats API via /stats/usage_by_month
=> Feature - add support for /stats/usage_by_month

lib/fastly/invoice.rb
This updates the `Invoice` class to use the `v2` endpoints and removes the deprecated endpoints.
* adds `list_invoices` to retrieve a list of all invoices
* adds `get_invoice_by_id` to get an invoice by id
=> Update fastly/invoice for v2 invoice endpoints

Gemfile, Rakefile, test/fastly/syslog_test.rb, test/test_helper.rb
* Gemfile: add rubocop. The Rakefile depended on rubocop test tasks, but we hadn't declared the dependency.
* syslog test: fix stubbed URL
* test_helper: require securerandom, which multiple tests use
* Rakefile: use Rake::TestTask to define `test:unit` task. Previously this task was defined as a shell 
command but it didn't actually run any of the unit tests.
=> 👷➕🐛✅ fix tests in CI

README.md
Seems right to link directly to API Reference here
=> Update Fastly docs url

.travis.yml
2.1 and 2.2 are EOL and bundler no longer supports them either.
=> update ruby versions to latest supported

fastly.gemspec, lib/fastly/client.rb
Based on this:  https://github.com/fastly/fastly-ruby/pull/139
Fixes #130
=> Use concurrent-ruby to handle thread safety for http client.

CHANGELOG.md, lib/fastly/gem_version.rb, lib/fastly/service.rb
`GET /service/:id/stats/:type` is deprecated and should be `GET /service/:id/stats/summary`
=> Correct stats API path

lib/fastly/backend.rb
Add the override_host field for the Backend API object
=> [Backend] Add override_host attribute for Backend

lib/fastly.rb, lib/fastly/client.rb, lib/fastly/token.rb, test/fastly/client_test.rb, test/fastly/token_test.rb, test/token_test.rb
A class file for token objects. Includes amendments to `client.rb` for authentication when creating new tokens.
=> Add tokens.rb

lib/fastly/gem_version.rb, test/fastly/client_test.rb, test/fastly/token_test.rb
Unit tests were failing because the gem version was bumped and the response `User-Agent` string contains the gem version. Use a pattern match for the `User-Agent` string so we don't have to change these tests each time we release a new gem.
=> Fix build error by using pattern match for User-Agent string

lib/fastly.rb, lib/fastly/client.rb, lib/fastly/gem_version.rb, lib/fastly/token.rb, test/api_key_test.rb, test/fastly/client_test.rb, test/fastly/customer_test.rb, test/fastly/dictionary_test.rb, test/fastly/syslog_test.rb, test/fastly/token_test.rb, test/full_login_test.rb
Removed the ability to authenticate with a username and password. Users are required to use api_key in order to be authorized.
=> Removes session authentication

lib/fastly/client.rb
Remove deprecation warning about Username and password signing in in the client
**What**
Now that the code pretaining to Authing in with Username and Password is removed, the deprecation warning in the client is not needed. To avoid further confusion, the warning is removed.
=> [fix] Remove deprecation warning about username and password

Gemfile, lib/fastly.rb, lib/fastly/client.rb, test/fastly/sumologic_logging_test.rb
The class for SumologicLogging was declared, but it was never included
in fastly.rb to autogenerate the methods to call anything.
I added a test, but didn't manually update the comment documentation in
fastly.rb, as that looks hand generated and out of date for arguments,
so I figured the test was more useful.
=> Fix SumologicLogging

.github/scripts/pack.sh, .github/scripts/publish.sh, .github/scripts/publish_env.sh, .github/scripts/release_body.sh, .github/workflows/ci-release.yaml
This PR adds a publish mechanism to allow this API client to publish itself to RubyGems and create a release in GitHub.
The input is to create a tag in this repo and push it, with the syntax: `release/[VERSION][-dry]`.
- `VERSION` should be the version number that the package should be published under, such as `v3.0.1` or `3.0.1-alpha.0` (leading `v` is optional and ignored)
- Specify `-dry` if you want to do a "dry run" which doesn't actually publish to RubyGems or create a release
This CI is intended to be used along with the client generator project, whose job it is to generate the newest API client code, tag it with said version code, and push it to this repo.
Unless running in `-dry` mode, this CI step will create a real version in RubyGems, and a release in GitHub. Example run using …
=> CI to automatically publish to RubyGems
